config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  get '/', to: "application#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/plant-with-most-comments', to: 'plants#most_comments', as: 'most_commented_plant'
  resources :users, except: [:index]
  
  resources :comments
  resources :plants do 
    resources :comments, only: [:index, :new]
  end
  resources :orders, only: [:index, :show] do
    resources :plants, only: [:index, :show]
  end

  resources :sessions, only: [:create]
  get '/login', to: 'users#login', as: 'login'
  post '/login', to: 'users#create_session'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/signup', to: 'users#signup', as: 'new'
  get '/auth/facebook/callback', to: 'sessions#facebook_create', as: 'facebook_login'
 
  

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :plant
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :plants
    validates :order, uniqueness: true
end

app/models/plant.rb
class Plant < ApplicationRecord
    belongs_to :order
    accepts_nested_attributes_for :order
    has_many :comments
    has_many :users, through: :comments
    validates :name, uniqueness: true 
    has_one_attached :img
    scope :order_by_name, -> { order(name: :asc) }
end

app/models/plant_type.rb
class PlantType < ApplicationRecord
    has_many :plants
end

app/models/user.rb
class User < ApplicationRecord
    has_many :plants
    has_many :messages
    has_many :comments
    has_many :orders, through: :plants
    has_secure_password
    validates :email, uniqueness: true
    validates :username, uniqueness: true
    validates :password, length: {minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :user_is_logged_in?, :plant_with_most_comments

    def current_user
        User.find_by_id(session[:user_id])
    end

    # def current_user_id
    #     if user_is_logged_in?
    #         session[:user_id]
    #     end
    # end

    def user_is_logged_in?
        !!session[:user_id]
    end
        
    def home
        render '/home'
    end

    # def own_plant?
    # end

    def plant_with_most_comments
        plants = Plant.all
        most_commented_plant = Plant.find(1)
        plants.each do |plant|
            if plant.comments.count > most_commented_plant.comments.count
                most_commented_plant = plant
            end
        end
        return most_commented_plant
    end

    

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index, :show]

    def index
        if params[:plant_id] 
            @comments = Plant.find(params[:plant_id]).comments
        else
            @comments = Comment.all
        end
    end

    def show
        @comment = Comment.find(params[:id])
        @plant = @comment.plant
    end

    def new
        if params[:plant_id]
            @comment = Comment.new(plant_id: params[:plant_id])
        else 
            @comment = Comment.new
        end
    end

    def edit
    end

    def create
        @comment = current_user.comments.build(comment_params)
        if @comment.save
            redirect_to @comment, notice: "Comment was sucessfully created."
        else
            render :new
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:title, :content, :plant_id, :user_id)
    end

    def require_login
        return head(:forbidden) unless session.include? :user_id
    end




end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @orders = Order.all 
    end

    def show
        @order = Order.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index, :show]

    def most_comments
        @plant = plant_with_most_comments
        render "show"
    end
    
    def index
        if params[:order_id]
            @plants = Order.find(params[:order_id]).plants
        else
            @plants = Plant.all.order_by_name 
        end
    end

    def show
        @plant = Plant.find(params[:id])
    end

    def new
        @plant = Plant.new
        # @plants = Plant.all
    end

    def create
        @plant = Plant.new(plant_params)
        if @plant.save
            redirect_to @plant
        else 
            render :new
        end
    end

    def edit 
        @plant = Plant.find_by(id: params[:id])
    end
    
    def update
        @plant = Plant.find_by(id: params[:id])
        if @plant.update(plant_params)
            redirect_to @plant, notice: 'Plant was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @plant = Plant.find_by(id: params[:id])
        @plant.destroy
        redirect_to plants_url, notice: 'Plant was successfully sucessfully deleted.'
    end


    private
    def plant_params
        params.require(:plant).permit(:img, :name, :species, :toxicity, :sunlight, :water, :propogation, :order_id)
    end

    def require_login
        return head(:forbidden) unless session.include? :user_id
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def login
    end

    def create
        user = User.find_by(email: params[:email]).try(:authenticate, params[:password])

        if !!user
            session[:user_id] = user.id
            redirect_to user
        else
            redirect to '/login'
        end

    end

    def facebook_create
      @user = User.find_or_create_by(email: auth['email']) do |u|
        u.name = auth['name']
        u.uid = auth['uid']
        u.password = SecureRandom.urlsafe_base64(5)
      end
        
      session[:user_id] = @user.id
        
      redirect_to '/'
    end
        

    def destroy 
        session[:user_id] = nil
        redirect_to '/'
    end

    private

  def auth
    request.env['omniauth.auth']["info"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    def index
        @users = User.all
    end
    
    def show
        @user = User.find_by(id: params[:id])
    end

   def signup
        @user = User.new
   end

   def login
        @user = User.new
   end


    def create_session
        user = User.find_by(username: params[:user][:username])

        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            redirect_to user_path(user.id)
        else
            redirect_to '/login', notice: "Incorrect Login or Password!"
        end
    end

    def edit
        @user = User.find_by(id: params[:id])
        if @user == current_user 
        else 
         redirect_to user_path(@user.id)
        end
    end

    def create
        user = User.new(user_params)
        if user.save
            session[:user_id] = user.id
            redirect_to user_path(user.id)
        else
            redirect_to '/signup'
        end
    end

    def update
        @user = User.find_by(id: params[:id])
        @user.update(user_params)
        redirect_to user_path(@user.id)
    end

    def destroy
        @user.destroy
        redirect_to '/', notice: 'Logged out!'
    end

    private
    def user_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :uid)
    end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/index.html.erb
<h1> Comments: </h1>
<ul> 
    <% @comments.each do |comment| %>
    <li> <a href="/comments/<%= comment.id %>"><%= comment.title %>
    <% end %>
</ul>     

    

app/views/comments/new.html.erb
<h1> New Comment </h1>
<%= form_for @comment do |f| %>
<%= f.label :plant %>
<% if @comment.plant_id == nil %>    
    <%= f.collection_select :plant_id, Plant.all, :id, :name %>
<% else %>
    <%= f.hidden_field :plant_id, value: @comment.plant_id %>
    <%= @comment.plant.name %> 
<% end %>     
<br>
<%= f.label :Title %>
<%= f.text_field :title %>
<br>
<%= f.label :Comment %>
<%= f.text_field :content %>
<br>
<%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<div class='content-wrapper'> 
<h1><%= @plant.name %></h1>
<% if @plant.img.attached? %>
    <img src="<%=(url_for(@plant.img))%>">
 <% end %>

<h3>Comment:</h3>
<%= @comment.title%>
<h3>Poster:</h3>
<%= @comment.user.name%>
<h3> Content:</h3>
<%= @comment.content%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <div class="main header">
    <title>Screenthumb</title>
  </div>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   
  <div class="d-flex justify-content-center">
  <div class="top-nav">
  <nav class="navbar navbar-expand-lg navbar-custom">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
   <ul class="nav nav-pills nav-fill">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
         <% if user_is_logged_in? %>
            <li class='nav-item'>
              <%= link_to current_user.name, current_user, class: 'text-light nav-link'%>
            </li>
           <% end %> 
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          User
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="/signup">Create Account</a>
          <a class="dropdown-item" href="/login">Login</a>
          <a class="dropdown-item" href="/logout">Logout</a>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Plants
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="/plants#index">View Plants</a>
          <a class="dropdown-item" href="/plants/new">New Plant</a>
          <a class="dropdown-item" href="/orders#index">Plant Family</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
</div>
</div>

 <%= yield %>



  </body>
</html>

app/views/orders/index.html.erb
<h1> Plant Orders </h1>
<ul>
    <% @orders.each do |order| %><br><br>
       <li> <a href="/orders/<%= order.id %>"><%= order.order %></a>
    <%end%>
    </li>
</ul>

app/views/orders/show.html.erb
<h1><%= @order.order %></h1>
<ul>
  <% @order.plants.each do |plant| %>
    <li><%=link_to plant.name, order_plant_path(@order.id, plant.id) %></li>
  <% end %>
</ul>

app/views/plants/_form.html.erb
<%= form_with(model: @plant, local: true) do |f| %>
<div class='content-wrapper'> 
    <%= f.label :Photo  %>
    <%= f.file_field :img%>
    <br>
    <%= f.label :name  %>
    <%= f.text_field  :name%>
    <br>
    <%= f.label :species  %>
    <%= f.text_field :species  %>
    <br>
    <%= f.label :toxicity  %>
    <br>
    <%= f.label :toxicity, 'Toxic'%>
    <%= f.radio_button :toxicity, true %>
    <%= f.label :toxicity, 'Nontoxic'%>
    <%= f.radio_button :toxicity, false %>
    <br>
    <%= f.label :sunlight  %>
    <%= f.text_field :sunlight  %>
    <br>
     <%= f.label :water  %>
    <%= f.text_field :water  %>
    <br>
     <%= f.label :propogation  %>
    <%= f.text_field :propogation  %>
    <br>
    <%= f.label :Order %>
    <%= f.collection_select :order_id, Order.all, :id, :order %>
    <br>
    <br>
    <p> Or Add New Order:</p>
      <%= f.fields_for :orders do |o| %>
        <%= o.label :order %>
        <%= o.text_field :order %>
        <br>
    <% end %>
    <br>

  <%= f.submit %>

</div>

<% end %>

app/views/plants/edit.html.erb
<h1> Edit Plant </h1>
<div class='content-wrapper'> 
<h2><%= @plant.name %></h2>
<%= render 'form', plant: @plant %>
<%= button_to "Delete Plant", @plant, method: 'delete', data: 
    {confirm: "Delete this plant? Action cannot be undone." } %>
</div>

app/views/plants/index.html.erb
<p><h1> Plants </h1><p>
<div class='invisible-wrapper'>
    <% @plants.each do |plant| %><br><br>
     <%= link_to plant, class: 'link-card' do %>
       <h3 class='plant'> <%= plant.name %></h3>
        <%end%>
    <% end %>
<div>    

app/views/plants/new.html.erb
<h1> Create a New Plant </h1>
<%= render 'form', plant: @plant %>

app/views/plants/show.html.erb
<h1><%= @plant.name %></h1>
<p id="notice"><%= notice %></p>
<div class='content-wrapper'> 
<% if @plant.img.attached? %>
    <%= image_tag(@plant.img) %>
   <%end%> 
<h3>Species:</h3>
<%=@plant.species%>
<br>
<h3>Sunlight Needed:</h3>
<%=@plant.sunlight%>
<br>
<h3>Toxicity:</h3>
<%=@plant.toxicity %>
<br>
<h3> Thirst: </h3>
<%= @plant.water %>
<h3> How to Propogate: </h3>
<%= @plant.propogation %>
<br>



<h2>Comments:</h2>
<% @plant.comments.each do |comment| %>
<li><%=link_to comment.title, plant_comments_path(@plant.id, comment.id) %></li>
<% end %>
<br>
<%= link_to 'Add Comment', new_plant_comment_path(:plant_id => @plant.id)  %>
<%= link_to 'Edit Plant', edit_plant_path(:id => @plant.id) %>

app/views/users/_form.html.erb
<div class='content-wrapper'> 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :username %>
    <%= text_field_tag "user[username]" %>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <%= text_field_tag "user[password]" %>
  </div>
   <div class="field" %>
    <%= label_tag :password_confirmation %>
    <%= password_field_tag "user[password_confirmation]" %>
  </div>
  </div>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= form_with model: @user do |f| %>
<%= render partial: "users/form", locals: {user: @user} %>
  <div class="actions">
    <%= f.submit "Edit" %>
  </div>
<% end %>
<%= button_to "Delete Account", @user, method: 'delete', data: 
    {confirm: "Delete account? Action cannot be undone." } %>
<%= link_to 'Back', user_path %>

app/views/users/login.html.erb
<h1> Log In</h1>
<div class='content-wrapper'> 
<p id="notice"><%= notice %></p>
<%= form_with(url: "/login")  do |f| %>
<%= render partial: "users/form", locals: {user: @user} %>
  <div class="actions">
    <%= f.submit "Log In" %>
  </div>
<% end %>
<%= link_to 'Back', root_path %>
</div>

app/views/users/new.html.erb
<h1> Sign Up! </h1>

<%= form_with model: @user do |f| %>
<div class="field" %>
 <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
<%= render partial: "users/form", locals: {user: @user} %>
   <div class="field" %>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>
   <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>
<div class='content-wrapper'> 
    <h2> Your Comments: </h2>
    <ul>
    <% @user.comments.each do |comment| %><br>
      <li> <h2><a href="/comments/<%= comment.id %>"><%= comment.title %></a></h2>
    <%end%>
    </li>
</ul>
</div>
<br>

<%= link_to 'Edit User', edit_user_path %>

app/views/users/signup.html.erb
<h1> Sign Up! </h1>
<div class='content-wrapper'> 
<p id="notice"><%= notice %></p>


<%= form_with model: @user do |f| %>
<div class="field" %>
 <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= label_tag :name %>
    <%= text_field_tag "user[name]" %>
  </div>
<%= render partial: "form", locals: {user: @user} %>
  
   <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>
<div>